name: Java CI

on: [push]

jobs:
  build:
    runs-on: [self-hosted,linux]

    steps:
      - uses: actions/checkout@v3
      - name: install sshkey
        run: |
          cd ~/.ssh
          
          
        
      
