name: Java CI

on: [push]

jobs:
  build:
    runs-on: linux

    steps:
      - uses: actions/checkout@v3
      - name: install putty
        run: |
          choco install putty.install --version=0.71
          
          
        
      
